/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FamiliesRouteImport } from './routes/families'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as AuthenticatedFamilyFamilyIdRouteImport } from './routes/_authenticated/family.$familyId'
import { Route as AuthenticatedRoomRoomIdRouteImport } from './routes/_authenticated/room.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesRoute = FamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFamilyFamilyIdRoute =
  AuthenticatedFamilyFamilyIdRouteImport.update({
    id: '/family/$familyId',
    path: '/family/$familyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomRoomIdRoute = AuthenticatedRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/families': typeof FamiliesRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/family/$familyId': typeof AuthenticatedFamilyFamilyIdRoute
  '/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/families': typeof FamiliesRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/family/$familyId': typeof AuthenticatedFamilyFamilyIdRoute
  '/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/families': typeof FamiliesRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/_authenticated/family/$familyId': typeof AuthenticatedFamilyFamilyIdRoute
  '/_authenticated/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/families'
    | '/feed'
    | '/leaderboard'
    | '/search'
    | '/admin'
    | '/me'
    | '/messages'
    | '/wallet'
    | '/profile/$userId'
    | '/family/$familyId'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/families'
    | '/feed'
    | '/leaderboard'
    | '/search'
    | '/admin'
    | '/me'
    | '/messages'
    | '/wallet'
    | '/profile/$userId'
    | '/family/$familyId'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/families'
    | '/feed'
    | '/leaderboard'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/me'
    | '/_authenticated/messages'
    | '/_authenticated/wallet'
    | '/profile/$userId'
    | '/_authenticated/family/$familyId'
    | '/_authenticated/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FamiliesRoute: typeof FamiliesRoute
  FeedRoute: typeof FeedRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SearchRoute: typeof SearchRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families': {
      id: '/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof FamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/family/$familyId': {
      id: '/_authenticated/family/$familyId'
      path: '/family/$familyId'
      fullPath: '/family/$familyId'
      preLoaderRoute: typeof AuthenticatedFamilyFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room/$roomId': {
      id: '/_authenticated/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedFamilyFamilyIdRoute: typeof AuthenticatedFamilyFamilyIdRoute
  AuthenticatedRoomRoomIdRoute: typeof AuthenticatedRoomRoomIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedFamilyFamilyIdRoute: AuthenticatedFamilyFamilyIdRoute,
  AuthenticatedRoomRoomIdRoute: AuthenticatedRoomRoomIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FamiliesRoute: FamiliesRoute,
  FeedRoute: FeedRoute,
  LeaderboardRoute: LeaderboardRoute,
  SearchRoute: SearchRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
